const std = @import("std");
const Extractor = @import("extract.zig").Extractor;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: {s} <output_zig_file> <input_object_file> [input_object_file2 ...]\n", .{args[0]});
        return;
    }

    const output_path = args[1];

    var all_results = std.ArrayListUnmanaged(Extractor.ExtractionResult){};
    defer all_results.deinit(allocator);

    // Iterate over all input files (args[2...])
    var arg_idx: usize = 2;
    while (arg_idx < args.len) : (arg_idx += 1) {
        const input_path = args[arg_idx];
        std.debug.print("[Generator] Processing: {s}\n", .{input_path});

        const file = try std.fs.cwd().openFile(input_path, .{});
        defer file.close();

        // Leaking file_bytes deliberately as slices depend on it.
        const file_bytes = try file.readToEndAlloc(allocator, 10 * 1024 * 1024);

        var extractor = Extractor.init(allocator, file_bytes);

        const results = extractor.extractAll("stencil_") catch |err| {
            std.debug.print("[Error] Failed to extract stencils from {s}: {}\n", .{ input_path, err });
            return err;
        };

        if (results.len == 0) {
            std.debug.print("[Warning] No stencils found matching 'stencil_*' in {s}\n", .{input_path});
        }

        try all_results.appendSlice(allocator, results);
    }

    const results = all_results.items;

    // Generate Output
    const out_path = output_path;
    {
        const out_file = try std.fs.cwd().createFile(out_path, .{});
        defer out_file.close();

        var buf: [4096]u8 = undefined;
        var file_buffered_writer = out_file.writer(&buf);
        const writer = &file_buffered_writer.interface;

        try writer.print("// Auto-generated by stencil_generator. Do not edit.\n\n", .{});
        try writer.print("pub const Relocation = struct {{ offset: u32, type: u4, symbol: []const u8, pcrel: bool }};\n\n", .{});

        for (results) |res| {
            // Compute Struct Name
            var struct_name_buf: [256]u8 = undefined;
            var struct_name: []u8 = &struct_name_buf;

            var short_name = res.name;
            if (std.mem.startsWith(u8, res.name, "stencil_")) {
                short_name = res.name["stencil_".len..];
            }

            @memcpy(struct_name[0..short_name.len], short_name);
            struct_name = struct_name[0..short_name.len];
            if (struct_name.len > 0) {
                struct_name[0] = std.ascii.toUpper(struct_name[0]);
            }

            try writer.print("pub const {s} = struct {{\n", .{struct_name});
            try writer.print("    pub const code = [_]u8{{", .{});

            for (res.code, 0..) |byte, i| {
                if (i % 16 == 0) try writer.print("\n        ", .{});
                try writer.print("0x{x:0>2}, ", .{byte});
            }

            try writer.print("\n    }};\n\n", .{});
            try writer.print("    pub const relocs = [_]Relocation{{\n", .{});

            for (res.relocations) |rel| {
                const sym = rel.symbol_name orelse "unknown";
                try writer.print("        .{{ .offset = {d}, .type = {d}, .symbol = \"{s}\", .pcrel = {} }},\n", .{ rel.offset, rel.type, sym, rel.pcrel });
            }

            try writer.print("    }};\n", .{});
            try writer.print("}};\n\n", .{});
        }

        try file_buffered_writer.end();
        std.debug.print("[Success] Generated {s} with {d} stencils\n", .{ out_path, results.len });
    }
}
